blueprint:
  name: Tesla Quatro Button
  description: Customizable blueprint for Tesla Quatro Button with optional actions for each button.
  domain: automation
  author: Kvehy
  input:
    device:
      name: Zařízení
      description: Choose device (Tesla Quatro Button)
      selector:
        device:
          integration: zha
    B_1_PRESS_sequence:
      name: Sequence for Button 1 - Press
      selector:
        action: {}
      default: []
    B_1_LONG_sequence:
      name: Sequence for Button 1 - Long Press
      selector:
        action: {}
      default: []
    B_1_DOUBLE_sequence:
      name: Sequence for Button 1 - Double Press
      selector:
        action: {}
      default: []
    B_2_PRESS_sequence:
      name: Sequence for Button 2 - Press
      selector:
        action: {}
      default: []
    B_2_LONG_sequence:
      name: Sequence for Button 2 - Long Press
      selector:
        action: {}
      default: []
    B_2_DOUBLE_sequence:
      name: Sequence for Button 2 - Double Press
      selector:
        action: {}
      default: []
    B_3_PRESS_sequence:
      name: Sequence for Button 3 - Press
      selector:
        action: {}
      default: []
    B_3_LONG_sequence:
      name: Sequence for Button 3 - Long Press
      selector:
        action: {}
      default: []
    B_3_DOUBLE_sequence:
      name: Sequence for Button 3 - Double Press
      selector:
        action: {}
      default: []
    B_4_PRESS_sequence:
      name: Sequence for Button 4 - Press
      selector:
        action: {}
      default: []
    B_4_LONG_sequence:
      name: Sequence for Button 4 - Long Press
      selector:
        action: {}
      default: []
    B_4_DOUBLE_sequence:
      name: Sequence for Button 4 - Double Press
      selector:
        action: {}
      default: []

trigger:
  - platform: device
    device_id: !input device
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    id: B_1_PRESS
  - platform: device
    device_id: !input device
    domain: zha
    type: remote_button_long_press
    subtype: button_1
    id: B_1_LONG
  - platform: device
    device_id: !input device
    domain: zha
    type: remote_button_double_press
    subtype: button_1
    id: B_1_DOUBLE
  - platform: device
    device_id: !input device
    domain: zha
    type: remote_button_short_press
    subtype: button_2
    id: B_2_PRESS
  - platform: device
    device_id: !input device
    domain: zha
    type: remote_button_long_press
    subtype: button_2
    id: B_2_LONG
  - platform: device
    device_id: !input device
    domain: zha
    type: remote_button_double_press
    subtype: button_2
    id: B_2_DOUBLE
  - platform: device
    device_id: !input device
    domain: zha
    type: remote_button_short_press
    subtype: button_3
    id: B_3_PRESS
  - platform: device
    device_id: !input device
    domain: zha
    type: remote_button_long_press
    subtype: button_3
    id: B_3_LONG
  - platform: device
    device_id: !input device
    domain: zha
    type: remote_button_double_press
    subtype: button_3
    id: B_3_DOUBLE
  - platform: device
    device_id: !input device
    domain: zha
    type: remote_button_short_press
    subtype: button_4
    id: B_4_PRESS
  - platform: device
    device_id: !input device
    domain: zha
    type: remote_button_long_press
    subtype: button_4
    id: B_4_LONG
  - platform: device
    device_id: !input device
    domain: zha
    type: remote_button_double_press
    subtype: button_4
    id: B_4_DOUBLE

action:
  - choose:
      - conditions:
          - condition: trigger
            id: B_1_PRESS
        sequence: !input B_1_PRESS_sequence
      - conditions:
          - condition: trigger
            id: B_1_LONG
        sequence: !input B_1_LONG_sequence
      - conditions:
          - condition: trigger
            id: B_1_DOUBLE
        sequence: !input B_1_DOUBLE_sequence
      - conditions:
          - condition: trigger
            id: B_2_PRESS
        sequence: !input B_2_PRESS_sequence
      - conditions:
          - condition: trigger
            id: B_2_LONG
        sequence: !input B_2_LONG_sequence
      - conditions:
          - condition: trigger
            id: B_2_DOUBLE
        sequence: !input B_2_DOUBLE_sequence
      - conditions:
          - condition: trigger
            id: B_3_PRESS
        sequence: !input B_3_PRESS_sequence
      - conditions:
          - condition: trigger
            id: B_3_LONG
        sequence: !input B_3_LONG_sequence
      - conditions:
          - condition: trigger
            id: B_3_DOUBLE
        sequence: !input B_3_DOUBLE_sequence
      - conditions:
          - condition: trigger
            id: B_4_PRESS
        sequence: !input B_4_PRESS_sequence
      - conditions:
          - condition: trigger
            id: B_4_LONG
        sequence: !input B_4_LONG_sequence
      - conditions:
          - condition: trigger
            id: B_4_DOUBLE
        sequence: !input B_4_DOUBLE_sequence

mode: single